### ISSUE TITLE
demo release 打包运行时闪退

### ISSUE THREAD

**Issue by leijingxing** [liuchuancong/gsy_video_player#5]
J4A_GetMethodID__catchAll: failed: readAt (J[BII)I
2024-10-22 14:21:53.958 22067-22067 AndroidRuntime          com.hyzh.gov                         D  Shutting down VM
2024-10-22 14:21:53.958 22067-22067 AndroidRuntime          com.hyzh.gov                         E  FATAL EXCEPTION: main
                                                                                                    Process: com.hyzh.gov, PID: 22067
                                                                                                    java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/~~CoLFuzH5OdYbaKF7jSZrVg==/com.hyzh.gov-qxsAj0huAryiGrW2_rIIiA==/lib/arm64/libijksdl.so"
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1661)
                                                                                                    	at tv.danmaku.ijk.media.player.IjkMediaPlayer$a.a(Unknown Source:0)
                                                                                                    	at tv.danmaku.ijk.media.player.IjkMediaPlayer.c2(Unknown Source:18)
                                                                                                    	at tv.danmaku.ijk.media.player.IjkMediaPlayer.b2(Unknown Source:0)
                                                                                                    	at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(Unknown Source:6)
                                                                                                    	at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(Unknown Source:2)
                                                                                                    	at ce.d.A(Unknown Source:6)
                                                                                                    	at wd.a.W(Unknown Source:50)
                                                                                                    	at wd.a.K(Unknown Source:0)
                                                                                                    	at wd.a$i.handleMessage(Unknown Source:54)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:211)
                                                                                                    	at android.os.Looper.loop(Looper.java:300)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8348)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

**Comment by leijingxing** [comment]
大哥,改下demo吧

**Comment by liuchuancong** [comment]
fork 看下吧 目前没精力 事儿多

**Comment by liuchuancong** [comment]
依赖是不是有问题，没问题啊
@leijingxing
